#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 sxhkd ksuperkey

sxhkd &

bspc monitor -d I II III IV V

#bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Galculator state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#303134"
bspc config normal_border_color         "#242427"
bspc config active_border_color         "#242427"

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Autostart Scripts:

wmname LG3D &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

bash $HOME/.fehbg &

# Bar
~/.config/bspwm/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
picom &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# double border
~/.config/bspwm/bin/bspborder
