#!/usr/bin/env bash

## Configurations --------------------------------------------#

hc() {
    herbstclient "$@"
}

hc emit_hook reload

## Autostart -------------------------------------------------#

bash ~/.config/herbstluftwm/scripts/herb_autostart

## keybindings -----------------------------------------------#

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier
Alt=Mod1   # Use alt as another modifier

# terminals
TERMINAL="kitty"
hc keybind $Mod-Return spawn "$TERMINAL"
hc keybind $Mod-Shift-Return spawn "$TERMINAL" --float
hc keybind $Mod-Alt-Return spawn "$TERMINAL" --full

# applications
FILE_MANAGER='thunar'
TEXT_EDITOR='geany'
WEB_BROWSER='firefox'
hc keybind $Mod-Shift-e spawn "$TEXT_EDITOR"
hc keybind $Mod-Shift-f spawn "$FILE_MANAGER"
hc keybind $Mod-Shift-w spawn "$WEB_BROWSER"

# rofi menus
hc keybind $Alt-F1 spawn "$HOME"/.config/herbstluftwm/scripts/rofi_launcher
hc keybind $Alt-F2 spawn "$HOME"/.config/herbstluftwm/scripts/rofi_runner
hc keybind $Mod-n spawn  "$HOME"/.config/herbstluftwm/scripts/network_menu
hc keybind $Mod-x spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_powermenu
hc keybind $Mod-m spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_music
hc keybind $Mod-s spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_screenshot
hc keybind $Mod-r spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_asroot
hc keybind $Mod-w spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_windows
hc keybind $Mod-b spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_bluetooth
hc keybind $Mod-t spawn  "$HOME"/.config/herbstluftwm/scripts/rofi_pdf 

# function keys
hc keybind XF86MonBrightnessUp 		spawn "$HOME/.config/herbstluftwm/scripts/herb_brightness" "--inc"
hc keybind XF86MonBrightnessDown 	spawn "$HOME/.config/herbstluftwm/scripts/herb_brightness" "--dec"
hc keybind XF86AudioRaiseVolume 	spawn "$HOME/.config/herbstluftwm/scripts/herb_volume" "--inc"
hc keybind XF86AudioLowerVolume 	spawn "$HOME/.config/herbstluftwm/scripts/herb_volume" "--dec"
hc keybind XF86AudioMute 			spawn "$HOME/.config/herbstluftwm/scripts/herb_volume" "--toggle"
hc keybind XF86AudioMicMute 		spawn "$HOME/.config/herbstluftwm/scripts/herb_volume" "--toggle-mic"
hc keybind XF86AudioNext 			spawn "mpc next"
hc keybind XF86AudioPrev 			spawn "mpc prev"
hc keybind XF86AudioPlay 			spawn "mpc toggle"
hc keybind XF86AudioStop 			spawn "mpc stop"

# screenshots
hc keybind Print 					spawn "$HOME/.config/herbstluftwm/scripts/herb_screenshot" "--now"
hc keybind $Alt-Print 				spawn "$HOME/.config/herbstluftwm/scripts/herb_screenshot" "--in5"
hc keybind Shift-Print 				spawn "$HOME/.config/herbstluftwm/scripts/herb_screenshot" "--in10"
hc keybind Control-Print 			spawn "$HOME/.config/herbstluftwm/scripts/herb_screenshot" "--win"
hc keybind $Mod-Print 				spawn "$HOME/.config/herbstluftwm/scripts/herb_screenshot" "--area"

# misc
hc keybind $Mod-p 					spawn "$HOME/.config/herbstluftwm/scripts/herb_colorpicker"
hc keybind Control-$Alt-m 			spawn "$HOME/.config/herbstluftwm/scripts/herb_music"
hc keybind Control-$Alt-l 			spawn "betterlockscreen" "--lock"
hc keybind $Mod-Escape 				spawn xkill

# window manager
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c close

# focusing clients, basic movement in tiling and floating mode
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# splitting frames, create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-s split explode
hc keybind $Mod-d remove

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Alt-Tab cycle
hc keybind $Mod-i jumpto urgent

## Mouse -----------------------------------------------------#

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

## Tags ------------------------------------------------------#

tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

## Layouts ---------------------------------------------------#

hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-space set_attr clients.focus.floating toggle
hc keybind $Mod-Control-space floating toggle

hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized

hc keybind $Mod-g pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

## Window rules ----------------------------------------------#

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class~'(alacritty-float)' focus=on floating=on
hc rule class~'(Pcmanfm|Onboard|Yad)' focus=on floating=on
hc rule class~'(Lxappearance|Nitrogen)' focus=on floating=on
hc rule class~'(Pavucontrol|Xfce4-power-manager-settings|Nm-connection-editor)' focus=on floating=on
hc rule class~'(feh|Viewnior|Gpicview|Gimp|MPlayer|Music)' focus=on floating=on
hc rule class~'(Kvantum Manager|qt5ct)' focus=on floating=on
hc rule class~'(VirtualBox Manager|qemu|Qemu-system-x86_64)' focus=on floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

## Theme -----------------------------------------------------#

# the frame
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set always_show_frame off
hc set frame_border_width 4
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 10

hc set frame_border_active_color '#EEEEEE'
hc set frame_border_normal_color '#262626'
hc set frame_bg_normal_color '#262626'
hc set frame_bg_active_color '#EEEEEE'

# containers
hc attr theme.title_font 'Liga SFMono Nerd Font:pixelsize=10'  # example using Xft
hc attr theme.title_height 34
hc attr theme.padding_top 12  # space below the title's baseline (i.e. text depth)
hc attr theme.padding_bottom 3
hc attr theme.padding_left 3
hc attr theme.padding_right 3
hc attr theme.inner_width 0
hc attr theme.active.outer_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0


# 1d2024
hc attr theme.active.color '#25292e'
hc attr theme.title_color '#25292e'
hc attr theme.normal.color '#161719'
hc attr theme.urgent.color '#D34651'
hc attr theme.normal.title_color '#161719'
hc attr theme.urgent.title_color '#D34651'
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#EEEEEE'
hc attr theme.urgent.inner_color '#D34651'
hc attr theme.normal.inner_color '#DADADA'
hc attr theme.background_color '#262626'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

hc set window_gap 25
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
